### ISSUE TITLE
Uncaught Exception when trying to start application simultaneously on different user accounts 

### ISSUE THREAD

**Issue by LsKs** [republicwireless-open/electron-single-instance#1]
In my project I need to ensure that each user has only one instance of application running at the same time. Everything works fine when only one user is logged to given machine, however when multiple users uses the application it starts with following error:

![error](https://cloud.githubusercontent.com/assets/8126512/10635213/f24f6fe2-77ee-11e5-8e39-d42e4341424f.PNG)

After clicking OK, it loads anyway.

**Comment by rmcshane** [comment]
Thanks for raising this issue and the pull request. Hadn't tested multi-user scenario.
